# Site settings
title: Schuyler
page_icon: https://github.com/schuyler-smith.png

background: https://github.com/schuyler-smith/photos/blob/main/morocco/43.jpg?raw=true

pages:
  - title: Home
    url: https://schuyler-smith.github.io/
  - title: About
    url: https://schuyler-smith.github.io/about
  - title: Publications
    url: https://schuyler-smith.github.io/publications
  - title: Projects
    url: https://schuyler-smith.github.io/projects
  - title: Software
    url: https://schuyler-smith.github.io/software
  - title: CV
    url: https://schuyler-smith.github.io/cv
